name: dartproject
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Your Name <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: "^0.11.3"
  firebase: "^5.0.1"

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.3.3
